1../firstvar.txt
1mconst.txt
1../aahead.txt
1../language.txt
1../aaconst.txt
1../aavars.txt
1../demo.txt
1../standard.txt
1../menu.txt
1../walkabou.txt
1../fx.txt
1../arcade.txt
1../vectors.txt
1../strategy.txt
1../comms.txt
1../floors.txt
1../goal.txt
1../cache.txt
1../duel.txt
1../fire.txt
1../movecurs.txt
1../spaniob.txt
1../music.txt
1../display.txt
1../print.txt
1../intro.txt
2B40
