#!/bin/bash

usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "--help: this usage message"
  echo "--bin: use a binary table.bin as input iso table.txt"
  echo "--old: for strict binary compatibility with older games"
  echo "--i8086: for strict binary compatibility with older games"
  echo
  exit 1
}

if ! type -P m68k-linux-gnu-as >/dev/null
then
  echo "Please install binutils-m68k-linux-gnu ..."
  echo "On Ubuntu Linux: sudo apt install binutils-m68k-linux-gnu"
  echo "On Rocky Linux:  sudo dnf install binutils-m68k-linux-gnu"
  echo
  usage
fi

bin=""
old=""
while [[ $# -gt 0 ]]
do
  case $1 in
    --help) usage ;;
    --bin) bin=$1 ;;
    --old) old=$1 ;;
  esac
  shift
done

if [[ ! -f table.txt ]]; then echo "The file table.txt was not found."; exit 2; fi

path=`dirname $0`
if [[ -z $bin ]]
then
  # assembler does not support case insensitive names
  cat table.txt | tr "[[:upper:]]" "[[:lower:]]" >table.s
  # assembler does not support ORG directive
  sed -i -e "s/^ org/;org/g" -e "/^ dc/s/,  */,/g" table.s
  # assembler wants to word-align every repeated instruction
  exp="`echo -e ' rept\n dc.b 0\n endr'`"
  act="`sed -ne '/rept/,/endr/{s/rept .*/rept/g;p}' table.s`"
  if [[ -n "$act" && "$act" != "$exp" ]]
  then
    echo "Warning: unsupported rept statement."
  else
    # adjust observed case: start aligned and repeat "dc.b 0"
    sed -i -e "s/^ rept \(.*\)/ rept (\1)\/2/g" table.s
    sed -i -e "/^ endr/a\ even" table.s
  fi
  $path/l9asm2bin table 2>/dev/null
  rm table.s
fi
$path/l9bin2tos table $old
if [[ -z $bin ]]; then rm table.bin; fi
mv table.prg table.dat
echo "Level 9 table.dat generation done."
echo
